//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pg_protoexport.Templates {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    
    public partial class Header : HeaderBase {
        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 6 "Header.tt"
            this.Write("% Auto generated by pg_protoexport ");
            
            #line default
            #line hidden
            
            #line 6 "Header.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( DateTime.Now.ToString("u") ));
            
            #line default
            #line hidden
            
            #line 6 "Header.tt"
            this.Write("\r\n");
            
            #line default
            #line hidden
            
            #line 7 "Header.tt"
 if (this.State.Standalone) { 
            
            #line default
            #line hidden
            
            #line 8 "Header.tt"
            this.Write(@"\documentclass[margin=8mm]{standalone}
\usepackage{inconsolata}
\renewcommand{\familydefault}{\ttdefault}
\usepackage{bytefield}
\usepackage{graphicx}
\usepackage{color}

\definecolor{lightcyan}{rgb}{0.84,1,1}
\definecolor{lightgreen}{rgb}{0.64,1,0.71}
\definecolor{lightergreen}{rgb}{0.74,1,0.81}
\definecolor{red}{rgb}{0.7,0,0}
\definecolor{lightred}{rgb}{1,0.7,0.71}
\definecolor{lightgray}{gray}{0.8}
\definecolor{nearlywhite}{gray}{0.99}

% White page background (not transparent) for image export.
% Uncolored bitboxes get nearlywhite fill so they are distinct from the background.
\let\oldbitbox\bitbox
\makeatletter
\renewcommand{\bitbox}[1]{%
  \@ifnextchar[{\oldbitbox{#1}}{\oldbitbox{#1}[bgcolor=nearlywhite]}%
}
\makeatother

\begin{document}
\pagecolor[gray]{1}
\begin{bytefield}[boxformatting={\centering\small}, bitheight=8ex]{");
            
            #line default
            #line hidden
            
            #line 34 "Header.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( this.State.Render.RowWidthBytes ));
            
            #line default
            #line hidden
            
            #line 34 "Header.tt"
            this.Write("}\r\n");
            
            #line default
            #line hidden
            
            #line 35 "Header.tt"
 
    if (!string.IsNullOrWhiteSpace(this.Message))
    {

            
            #line default
            #line hidden
            
            #line 39 "Header.tt"
            this.Write("    \r\n");
            
            #line default
            #line hidden
            
            #line 40 "Header.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( this.Message ));
            
            #line default
            #line hidden
            
            #line 40 "Header.tt"
            this.Write("\r\n\r\n");
            
            #line default
            #line hidden
            
            #line 42 "Header.tt"
 
    }
} else { 
            
            #line default
            #line hidden
            
            #line 45 "Header.tt"
            this.Write(@"\documentclass{article}
\usepackage{inconsolata}
\renewcommand{\familydefault}{\ttdefault}
\usepackage[margin=1.3cm,a4paper]{geometry}% http://ctan.org/pkg/geometry
\usepackage{bytefield}
\usepackage{graphicx}
\usepackage{color}

\definecolor{lightcyan}{rgb}{0.84,1,1}
\definecolor{lightgreen}{rgb}{0.64,1,0.71}
\definecolor{lightergreen}{rgb}{0.74,1,0.81}
\definecolor{lightred}{rgb}{1,0.7,0.71}
\definecolor{lightgray}{gray}{0.8}
\definecolor{nearlywhite}{gray}{0.99}

% White page background (not transparent) for image export.
% Uncolored bitboxes get nearlywhite fill so they are distinct from the background.
\let\oldbitbox\bitbox
\makeatletter
\renewcommand{\bitbox}[1]{%
  \@ifnextchar[{\oldbitbox{#1}}{\oldbitbox{#1}[bgcolor=nearlywhite]}%
}
\makeatother

\begin{document}
\pagecolor[gray]{1}

");
            
            #line default
            #line hidden
            
            #line 72 "Header.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( this.Message ));
            
            #line default
            #line hidden
            
            #line 72 "Header.tt"
            this.Write("\r\n\r\nPackets are grouped in conversations.\r\nA conversation ends when backend is is" +
                    "suing a ReadyForQuery message.\r\n\r\n\\section{Conversation}\r\n\r\n");
            
            #line default
            #line hidden
            
            #line 79 "Header.tt"
 } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
        }
    }
    
    public class HeaderBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
