//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pg_protoexport.Templates {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    
    public partial class Bind : BindBase {
        
        
        #line 125 "Bind.tt"
 float ITextTransformer.EstimateBytefieldRowCount() =>
        this.Render.Exact
            ? LatexHelper.CountExactRowsForMessage(this.Length, this.Render.RowWidthBytes)
            : 4;

        #line default
        #line hidden
        
        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 6 "Bind.tt"
 if (this.Render.Exact) {
    int rowWidth = this.Render.RowWidthBytes;
    int usedBytes = 5; // 1 byte code + 4 bytes length header

            
            #line default
            #line hidden
            
            #line 10 "Bind.tt"
            this.Write("\\begin{leftwordgroup}{Bind}\n    \\bitbox{1}[bgcolor=lightcyan]{B} &\n    \\bitbox{4}" +
                    "[bgcolor=lightgreen]{length: ");
            
            #line default
            #line hidden
            
            #line 12 "Bind.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( this.Length ));
            
            #line default
            #line hidden
            
            #line 12 "Bind.tt"
            this.Write("}");
            
            #line default
            #line hidden
            
            #line 12 "Bind.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.EmitWrappingCString("portal: ", this.Message.PortalName, rowWidth, ref usedBytes) ));
            
            #line default
            #line hidden
            
            #line 12 "Bind.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.EmitWrappingCString("statement: ", this.Message.StatementName, rowWidth, ref usedBytes) ));
            
            #line default
            #line hidden
            
            #line 12 "Bind.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.EmitFixedBitbox("paramFormats: " + this.ParamFormatCount, 2, rowWidth, ref usedBytes, bgcolor: "lightergreen") ));
            
            #line default
            #line hidden
            
            #line 12 "Bind.tt"

    foreach (short fmt in this.ParamFormats)
    {
    
            
            #line default
            #line hidden
            
            #line 16 "Bind.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.EmitFixedBitbox(LatexHelper.ToFormatString(fmt), 2, rowWidth, ref usedBytes) ));
            
            #line default
            #line hidden
            
            #line 16 "Bind.tt"

    }
    
            
            #line default
            #line hidden
            
            #line 19 "Bind.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.EmitFixedBitbox("paramValues: " + this.ParamValuesCount, 2, rowWidth, ref usedBytes, bgcolor: "lightergreen") ));
            
            #line default
            #line hidden
            
            #line 19 "Bind.tt"

    int paramIdx = 0;
    foreach ((int Length, byte[] Data) v in this.ParamValues)
    {
        paramIdx++;
    
            
            #line default
            #line hidden
            
            #line 25 "Bind.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.EmitFixedBitbox("length" + paramIdx + ": " + v.Length, 4, rowWidth, ref usedBytes, bgcolor: "lightergreen") ));
            
            #line default
            #line hidden
            
            #line 25 "Bind.tt"

        if (v.Length > 0)
        {
            string hex = Convert.ToHexStringLower(v.Data);
    
            
            #line default
            #line hidden
            
            #line 30 "Bind.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.EmitWrappingBitboxes("p" + paramIdx + ": ", hex, v.Length, rowWidth, ref usedBytes) ));
            
            #line default
            #line hidden
            
            #line 30 "Bind.tt"

        }
    }
    
            
            #line default
            #line hidden
            
            #line 34 "Bind.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.EmitFixedBitbox("resultFormats: " + this.ResultFormatsCount, 2, rowWidth, ref usedBytes, bgcolor: "lightergreen") ));
            
            #line default
            #line hidden
            
            #line 34 "Bind.tt"

    foreach (short rf in this.ResultFormats)
    {
    
            
            #line default
            #line hidden
            
            #line 38 "Bind.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.EmitFixedBitbox(LatexHelper.ToFormatString(rf), 2, rowWidth, ref usedBytes) ));
            
            #line default
            #line hidden
            
            #line 38 "Bind.tt"

    }
    
            
            #line default
            #line hidden
            
            #line 41 "Bind.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.EmitPadToRowEnd(ref usedBytes, rowWidth) ));
            
            #line default
            #line hidden
            
            #line 41 "Bind.tt"
            this.Write("\n\\end{leftwordgroup}\n");
            
            #line default
            #line hidden
            
            #line 43 "Bind.tt"
 } else { 
            
            #line default
            #line hidden
            
            #line 44 "Bind.tt"
            this.Write("\n\\begin{leftwordgroup}{Bind}\n    \\bitbox{1}[bgcolor=lightcyan]{B} &\n    \\bitbox{4" +
                    "}[bgcolor=lightgreen]{length: ");
            
            #line default
            #line hidden
            
            #line 47 "Bind.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( this.Length ));
            
            #line default
            #line hidden
            
            #line 47 "Bind.tt"
            this.Write("} &\n    \\bitbox{13}{portal:");
            
            #line default
            #line hidden
            
            #line 48 "Bind.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( this.Portal ));
            
            #line default
            #line hidden
            
            #line 48 "Bind.tt"
            this.Write("} &\n    \\bitbox{14}{statement:");
            
            #line default
            #line hidden
            
            #line 49 "Bind.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.Unescape(this.Statement) ));
            
            #line default
            #line hidden
            
            #line 49 "Bind.tt"
            this.Write("}\n\n    \\\\\n\n    \\begin{rightwordgroup}{\\small Parameter formats}\n        \\bitbox{2" +
                    "}[bgcolor=lightergreen]{\\rotatebox{90}{\\tiny count:");
            
            #line default
            #line hidden
            
            #line 54 "Bind.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( this.ParamFormatCount ));
            
            #line default
            #line hidden
            
            #line 54 "Bind.tt"
            this.Write("}} &\n");
            
            #line default
            #line hidden
            
            #line 55 "Bind.tt"

int formatIndex = 0;
foreach (short format in this.ParamFormats)
{

            
            #line default
            #line hidden
            
            #line 60 "Bind.tt"
            this.Write("         \\bitbox{2}{\\rotatebox{90}{\\tiny ");
            
            #line default
            #line hidden
            
            #line 60 "Bind.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.ToFormatString(format) ));
            
            #line default
            #line hidden
            
            #line 60 "Bind.tt"
            this.Write("}} &\n");
            
            #line default
            #line hidden
            
            #line 61 "Bind.tt"

    formatIndex++;
}

            
            #line default
            #line hidden
            
            #line 65 "Bind.tt"
            this.Write("        \\bitbox{");
            
            #line default
            #line hidden
            
            #line 65 "Bind.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( 30 - 2 * formatIndex ));
            
            #line default
            #line hidden
            
            #line 65 "Bind.tt"
            this.Write("}[bgcolor=lightgray]{}\n    \\end{rightwordgroup}  \\\\\n\n    \\begin{rightwordgroup}{\\" +
                    "small Parameter values \\\\ \\tiny \\it unspecified (OUT params): \\\\ \\tiny \\it lengt" +
                    "h=-1, no value}\n        \\bitbox{2}[bgcolor=lightergreen]{\\rotatebox{90}{\\tiny co" +
                    "unt:");
            
            #line default
            #line hidden
            
            #line 69 "Bind.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( this.ParamValuesCount ));
            
            #line default
            #line hidden
            
            #line 69 "Bind.tt"
            this.Write("}} &\n");
            
            #line default
            #line hidden
            
            #line 70 "Bind.tt"

// fields are length+data except for null fields (only length)
int valuesIndex = 0;
int usedBytes = 2;
foreach ((int Length, byte[] Data) value in this.ParamValues)
{
    CheckOverflow(ref usedBytes, 4);
    valuesIndex++;
    usedBytes += 4;


            
            #line default
            #line hidden
            
            #line 81 "Bind.tt"
            this.Write("      \\bitbox{4}[bgcolor=lightergreen]{\\small length");
            
            #line default
            #line hidden
            
            #line 81 "Bind.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( valuesIndex ));
            
            #line default
            #line hidden
            
            #line 81 "Bind.tt"
            this.Write(": ");
            
            #line default
            #line hidden
            
            #line 81 "Bind.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( value.Length ));
            
            #line default
            #line hidden
            
            #line 81 "Bind.tt"
            this.Write("} & ");
            
            #line default
            #line hidden
            
            #line 81 "Bind.tt"

    if (value.Length != -1)
    {
        usedBytes += 4;

            
            #line default
            #line hidden
            
            #line 86 "Bind.tt"
            this.Write("      \\bitbox{4}{\\small param");
            
            #line default
            #line hidden
            
            #line 86 "Bind.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( valuesIndex ));
            
            #line default
            #line hidden
            
            #line 86 "Bind.tt"
            this.Write(" data} & ");
            
            #line default
            #line hidden
            
            #line 86 "Bind.tt"

    }
}

            
            #line default
            #line hidden
            
            #line 90 "Bind.tt"
            this.Write("        \\bitbox{");
            
            #line default
            #line hidden
            
            #line 90 "Bind.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( 32 - usedBytes ));
            
            #line default
            #line hidden
            
            #line 90 "Bind.tt"
            this.Write("}[bgcolor=lightgray]{}\n    \\end{rightwordgroup}  \\\\\n\n\n    \\begin{rightwordgroup}{" +
                    "\\small Result formats \\\\ \\tiny 0 (text) or 1 (binary)}\n        \\bitbox{2}[bgcolo" +
                    "r=lightergreen]{\\rotatebox{90}{\\tiny count:");
            
            #line default
            #line hidden
            
            #line 95 "Bind.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( this.ResultFormatsCount ));
            
            #line default
            #line hidden
            
            #line 95 "Bind.tt"
            this.Write("}} &\n");
            
            #line default
            #line hidden
            
            #line 96 "Bind.tt"

    int resultFormatIndex = 0;
    foreach (var f in this.ResultFormats)
    {

            
            #line default
            #line hidden
            
            #line 101 "Bind.tt"
            this.Write("      \\bitbox{2}{\\rotatebox{90}{\\tiny ");
            
            #line default
            #line hidden
            
            #line 101 "Bind.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.ToFormatString(f) ));
            
            #line default
            #line hidden
            
            #line 101 "Bind.tt"
            this.Write("}} & ");
            
            #line default
            #line hidden
            
            #line 101 "Bind.tt"


        resultFormatIndex++;
     }

            
            #line default
            #line hidden
            
            #line 106 "Bind.tt"
            this.Write("        \\bitbox{");
            
            #line default
            #line hidden
            
            #line 106 "Bind.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( 32 - 2 - 2 * resultFormatIndex ));
            
            #line default
            #line hidden
            
            #line 106 "Bind.tt"
            this.Write("}[bgcolor=lightgray]{}\n    \\end{rightwordgroup}\n\n\\end{leftwordgroup}\n");
            
            #line default
            #line hidden
            
            #line 110 "Bind.tt"
 } 
            
            #line default
            #line hidden
            
            #line 111 "Bind.tt"
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 112 "Bind.tt"

    void CheckOverflow(ref int usedBytes, int bytesRequested)
    {
        int spaceLeft = 32 - usedBytes;
        if (spaceLeft >= bytesRequested)
            return;

        // need to go to new line
        usedBytes = 0;

            
            #line default
            #line hidden
            
            #line 122 "Bind.tt"
            this.Write("      \\bitbox{");
            
            #line default
            #line hidden
            
            #line 122 "Bind.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( spaceLeft ));
            
            #line default
            #line hidden
            
            #line 122 "Bind.tt"
            this.Write("}[bgcolor=lightgray]{} \\\\ ");
            
            #line default
            #line hidden
            
            #line 122 "Bind.tt"

    }

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
        }
    }
    
    public class BindBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
