//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pg_protoexport.Templates {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;


    public partial class CopyData : CopyDataBase {


        #line 64 "CopyData.tt"
 float ITextTransformer.EstimateBytefieldRowCount() =>
        this.Render.Exact
            ? LatexHelper.CountExactRowsForMessage(this.Length, this.Render.RowWidthBytes)
            : 1f;

        #line default
        #line hidden


        public virtual string TransformText() {
            this.GenerationEnvironment = null;

            if (this.Render.Exact) {
                int rowWidth = this.Render.RowWidthBytes;
                int usedBytes = 5;
                if (this.IsHeader) {
                    string sigLabel = "sig: " + (this.SignatureValid ? "PGCOPY OK" : "MISMATCH");
                    string flagsLabel = "flags: " + this.FlagsHex;
                    string extLenLabel = "ext-len: " + this.HeaderExtensionLength;
                    this.Write("\\begin{leftwordgroup}{CopyData (binary header)}\n        \\bitbox{1}[bgcolor=lightcyan]{d} &\n        \\bitbox{4}[bgcolor=lightgreen]{length: ");
                    this.Write(this.ToStringHelper.ToStringWithCulture(this.Length));
                    this.Write("}");
                    this.Write(this.ToStringHelper.ToStringWithCulture(LatexHelper.EmitFixedBitbox(sigLabel, 11, rowWidth, ref usedBytes)));
                    this.Write(this.ToStringHelper.ToStringWithCulture(LatexHelper.EmitFixedBitbox(flagsLabel, 4, rowWidth, ref usedBytes)));
                    this.Write(this.ToStringHelper.ToStringWithCulture(LatexHelper.EmitFixedBitbox(extLenLabel, 4, rowWidth, ref usedBytes)));
                    if (this.HeaderExtensionPreviewLength > 0) {
                        this.Write(this.ToStringHelper.ToStringWithCulture(LatexHelper.EmitFixedBitbox("ext (" + this.HeaderExtensionPreviewLength + "b)", System.Math.Min(this.HeaderExtensionPreviewLength, rowWidth), rowWidth, ref usedBytes)));
                    }
                    int tupleBytes = this.DataLength - 19 - this.HeaderExtensionPreviewLength;
                    if (tupleBytes > 0) {
                        int tupleCell = System.Math.Min(tupleBytes, rowWidth - usedBytes > 0 ? rowWidth - usedBytes : rowWidth);
                        this.Write(this.ToStringHelper.ToStringWithCulture(LatexHelper.EmitFixedBitbox("tuple (" + tupleBytes + "b)", tupleCell, rowWidth, ref usedBytes)));
                    }
                    this.Write(this.ToStringHelper.ToStringWithCulture(LatexHelper.EmitPadToRowEnd(ref usedBytes, rowWidth)));
                    this.Write("\n    \\end{leftwordgroup}\n");
                } else if (this.IsTrailer) {
                    this.Write("\\begin{leftwordgroup}{CopyData (binary trailer)}\n        \\bitbox{1}[bgcolor=lightcyan]{d} &\n        \\bitbox{4}[bgcolor=lightgreen]{length: ");
                    this.Write(this.ToStringHelper.ToStringWithCulture(this.Length));
                    this.Write("}");
                    this.Write(this.ToStringHelper.ToStringWithCulture(LatexHelper.EmitFixedBitbox("trailer: FF FF", 2, rowWidth, ref usedBytes)));
                    this.Write(this.ToStringHelper.ToStringWithCulture(LatexHelper.EmitPadToRowEnd(ref usedBytes, rowWidth)));
                    this.Write("\n    \\end{leftwordgroup}\n");
                } else {
                    string label = "data (" + this.DataLength + " bytes" + (this.Truncated ? ", preview" : "") + (this.IsBinary ? ", binary tuple" : "") + ")";
                    this.Write("\\begin{leftwordgroup}{CopyData}\n        \\bitbox{1}[bgcolor=lightcyan]{d} &\n        \\bitbox{4}[bgcolor=lightgreen]{length: ");
                    this.Write(this.ToStringHelper.ToStringWithCulture(this.Length));
                    this.Write("}");
                    this.Write(this.ToStringHelper.ToStringWithCulture(LatexHelper.EmitFixedBitbox(label, 8, rowWidth, ref usedBytes)));
                    this.Write(this.ToStringHelper.ToStringWithCulture(LatexHelper.EmitPadToRowEnd(ref usedBytes, rowWidth)));
                    this.Write("\n    \\end{leftwordgroup}\n");
                }
            } else {
                if (this.IsHeader) {
                    this.Write("\n\\begin{leftwordgroup}{CopyData (binary header)}\n        \\bitbox{1}[bgcolor=lightcyan]{d} &\n        \\bitbox{4}[bgcolor=lightgreen]{length: ");
                    this.Write(this.ToStringHelper.ToStringWithCulture(this.Length));
                    this.Write("} &\n        \\bitbox{11}{\\tiny sig: ");
                    this.Write(this.ToStringHelper.ToStringWithCulture(this.SignatureValid ? "PGCOPY OK" : "MISMATCH"));
                    this.Write("} &\n        \\bitbox{4}{\\tiny flags: ");
                    this.Write(this.ToStringHelper.ToStringWithCulture(this.FlagsHex));
                    this.Write("} &\n        \\bitbox{4}{\\tiny ext-len: ");
                    this.Write(this.ToStringHelper.ToStringWithCulture(this.HeaderExtensionLength));
                    this.Write("} &\n        \\bitbox{8}[bgcolor=lightgray]{\\tiny ");
                    this.Write(this.ToStringHelper.ToStringWithCulture(this.PreviewHex));
                    this.Write("}\n    \\end{leftwordgroup}\n");
                } else if (this.IsTrailer) {
                    this.Write("\n\\begin{leftwordgroup}{CopyData (binary trailer)}\n        \\bitbox{1}[bgcolor=lightcyan]{d} &\n        \\bitbox{4}[bgcolor=lightgreen]{length: ");
                    this.Write(this.ToStringHelper.ToStringWithCulture(this.Length));
                    this.Write("} &\n        \\bitbox{2}{\\tiny FF FF} &\n        \\bitbox{25}[bgcolor=lightgray]{\\tiny end-of-stream}\n    \\end{leftwordgroup}\n");
                } else {
                    this.Write("\n\\begin{leftwordgroup}{CopyData");
                    this.Write(this.ToStringHelper.ToStringWithCulture(this.IsBinary ? " (binary tuple)" : ""));
                    this.Write("}\n        \\bitbox{1}[bgcolor=lightcyan]{d} &\n        \\bitbox{4}[bgcolor=lightgreen]{length: ");
                    this.Write(this.ToStringHelper.ToStringWithCulture(this.Length));
                    this.Write("} &\n        \\bitbox{8}{\\tiny data: ");
                    this.Write(this.ToStringHelper.ToStringWithCulture(this.DataLength));
                    this.Write(" bytes");
                    this.Write(this.ToStringHelper.ToStringWithCulture(this.Truncated ? " (preview)" : ""));
                    this.Write("} &\n        \\bitbox{19}[bgcolor=lightgray]{\\tiny ");
                    this.Write(this.ToStringHelper.ToStringWithCulture(this.PreviewHex));
                    this.Write("}\n    \\end{leftwordgroup}\n");
                }
            }
            return this.GenerationEnvironment.ToString();
        }

        public virtual void Initialize() {
        }
    }

    public class CopyDataBase {

        private global::System.Text.StringBuilder builder;

        private global::System.Collections.Generic.IDictionary<string, object> session;

        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;

        private string currentIndent = string.Empty;

        private global::System.Collections.Generic.Stack<int> indents;

        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();

        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }

        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }

        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }

        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }

        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }

        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }

        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }

        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }

        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }

        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }

        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }

        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }

        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }

        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }

        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }

        public class ToStringInstanceHelper {

            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;

            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }

            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
