//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pg_protoexport.Templates {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    
    public partial class CopyInResponse : CopyInResponseBase {
        
        
        #line 36 "CopyInResponse.tt"
 float ITextTransformer.EstimateBytefieldRowCount() =>
        this.Render.Exact
            ? LatexHelper.CountExactRowsForMessage(this.Length, this.Render.RowWidthBytes)
            : 1f;

        #line default
        #line hidden
        
        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 6 "CopyInResponse.tt"
 if (this.Render.Exact) {
    int rowWidth = this.Render.RowWidthBytes;
    int usedBytes = 5;
    string fmtLabel = this.OverallFormat == 1 ? "binary" : "text";

            
            #line default
            #line hidden
            
            #line 11 "CopyInResponse.tt"
            this.Write("\\begin{leftwordgroup}{CopyInResponse}\n        \\bitbox{1}[bgcolor=lightcyan]{G} &\n" +
                    "        \\bitbox{4}[bgcolor=lightgreen]{length: ");
            
            #line default
            #line hidden
            
            #line 13 "CopyInResponse.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( this.Length ));
            
            #line default
            #line hidden
            
            #line 13 "CopyInResponse.tt"
            this.Write("}");
            
            #line default
            #line hidden
            
            #line 13 "CopyInResponse.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.EmitFixedBitbox("fmt: " + fmtLabel, 1, rowWidth, ref usedBytes) ));
            
            #line default
            #line hidden
            
            #line 13 "CopyInResponse.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.EmitFixedBitbox("cols: " + this.ColumnCount, 2, rowWidth, ref usedBytes) ));
            
            #line default
            #line hidden
            
            #line 13 "CopyInResponse.tt"

    int colIdx = 0;
    foreach (var col in this.ColumnFormats)
    {
        colIdx++;
    
            
            #line default
            #line hidden
            
            #line 19 "CopyInResponse.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.EmitFixedBitbox("col" + colIdx + ": " + (col == 1 ? "bin" : "txt"), 2, rowWidth, ref usedBytes) ));
            
            #line default
            #line hidden
            
            #line 19 "CopyInResponse.tt"

    }
    
            
            #line default
            #line hidden
            
            #line 22 "CopyInResponse.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.EmitPadToRowEnd(ref usedBytes, rowWidth) ));
            
            #line default
            #line hidden
            
            #line 22 "CopyInResponse.tt"
            this.Write("\n    \\end{leftwordgroup}\n");
            
            #line default
            #line hidden
            
            #line 24 "CopyInResponse.tt"
 } else {
    string fmtLabel = this.OverallFormat == 1 ? "binary" : "text";

            
            #line default
            #line hidden
            
            #line 27 "CopyInResponse.tt"
            this.Write("\n\\begin{leftwordgroup}{CopyInResponse}\n        \\bitbox{1}[bgcolor=lightcyan]{G} &" +
                    "\n        \\bitbox{4}[bgcolor=lightgreen]{length: ");
            
            #line default
            #line hidden
            
            #line 30 "CopyInResponse.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( this.Length ));
            
            #line default
            #line hidden
            
            #line 30 "CopyInResponse.tt"
            this.Write("} &\n        \\bitbox{2}{\\tiny fmt: ");
            
            #line default
            #line hidden
            
            #line 31 "CopyInResponse.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( fmtLabel ));
            
            #line default
            #line hidden
            
            #line 31 "CopyInResponse.tt"
            this.Write("} &\n        \\bitbox{2}{\\tiny cols: ");
            
            #line default
            #line hidden
            
            #line 32 "CopyInResponse.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( this.ColumnCount ));
            
            #line default
            #line hidden
            
            #line 32 "CopyInResponse.tt"
            this.Write("} &\n        \\bitbox{23}[bgcolor=lightgray]{\\tiny ");
            
            #line default
            #line hidden
            
            #line 33 "CopyInResponse.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( string.Join(", ", this.ColumnFormats.Select(c => c == 1 ? "bin" : "txt")) ));
            
            #line default
            #line hidden
            
            #line 33 "CopyInResponse.tt"
            this.Write("}\n    \\end{leftwordgroup}\n");
            
            #line default
            #line hidden
            
            #line 35 "CopyInResponse.tt"
 } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
        }
    }
    
    public class CopyInResponseBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
