//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pg_protoexport.Templates {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    
    public partial class DataRow : DataRowBase {
        
        
        #line 78 "DataRow.tt"
 float ITextTransformer.EstimateBytefieldRowCount() =>
        this.Render.Exact
            ? LatexHelper.CountExactRowsForMessage(this.Length, this.Render.RowWidthBytes)
            : 1 + this.Fields.Count;

        #line default
        #line hidden
        
        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 6 "DataRow.tt"
 if (this.Render.Exact) {
    int rowWidth = this.Render.RowWidthBytes;
    int usedBytes = 5; // 1 byte code + 4 bytes length header

            
            #line default
            #line hidden
            
            #line 10 "DataRow.tt"
            this.Write("    \\begin{leftwordgroup}{DataRow}\n        \\bitbox{1}[bgcolor=lightcyan]{D} &\n   " +
                    "     \\bitbox{4}[bgcolor=lightgreen]{length: ");
            
            #line default
            #line hidden
            
            #line 12 "DataRow.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( this.Length ));
            
            #line default
            #line hidden
            
            #line 12 "DataRow.tt"
            this.Write("}");
            
            #line default
            #line hidden
            
            #line 12 "DataRow.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.EmitFixedBitbox("fields: " + this.FieldCount, 2, rowWidth, ref usedBytes) ));
            
            #line default
            #line hidden
            
            #line 12 "DataRow.tt"

    foreach (var f in this.Fields)
    {
        // 4-byte int32 length prefix per column.
    
            
            #line default
            #line hidden
            
            #line 17 "DataRow.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.EmitFixedBitbox("length: " + f.Length, 4, rowWidth, ref usedBytes, bgcolor: "lightergreen") ));
            
            #line default
            #line hidden
            
            #line 17 "DataRow.tt"

        if (f.Length > 0)
        {
            if (f.IsText)
            {
    
            
            #line default
            #line hidden
            
            #line 23 "DataRow.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.EmitWrappingBitboxes(null, f.RawText, f.Length, rowWidth, ref usedBytes) ));
            
            #line default
            #line hidden
            
            #line 23 "DataRow.tt"

            }
            else if (f.Length <= rowWidth)
            {
                // Binary: emit full hex pairs as a label in a single byte-accurate cell.
    
            
            #line default
            #line hidden
            
            #line 29 "DataRow.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.EmitFixedBitbox(f.RawText, f.Length, rowWidth, ref usedBytes) ));
            
            #line default
            #line hidden
            
            #line 29 "DataRow.tt"

            }
            else
            {
                // Long binary: wrap the hex stream; one hex byte == one wire byte.
    
            
            #line default
            #line hidden
            
            #line 35 "DataRow.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.EmitWrappingBitboxes(null, f.RawText, f.Length, rowWidth, ref usedBytes) ));
            
            #line default
            #line hidden
            
            #line 35 "DataRow.tt"

            }
        }
    }
    
            
            #line default
            #line hidden
            
            #line 40 "DataRow.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.EmitPadToRowEnd(ref usedBytes, rowWidth) ));
            
            #line default
            #line hidden
            
            #line 40 "DataRow.tt"
            this.Write("\n    \\end{leftwordgroup}\n");
            
            #line default
            #line hidden
            
            #line 42 "DataRow.tt"
 } else { 
            
            #line default
            #line hidden
            
            #line 43 "DataRow.tt"
            this.Write("\n    \\begin{leftwordgroup}{DataRow}\n        \\bitbox{1}[bgcolor=lightcyan]{D} &\n  " +
                    "      \\bitbox{4}[bgcolor=lightgreen]{length: ");
            
            #line default
            #line hidden
            
            #line 46 "DataRow.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( this.Length ));
            
            #line default
            #line hidden
            
            #line 46 "DataRow.tt"
            this.Write("} &\n        \\bitbox{2}{\\rotatebox{90}{\\tiny fields: ");
            
            #line default
            #line hidden
            
            #line 47 "DataRow.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( this.FieldCount ));
            
            #line default
            #line hidden
            
            #line 47 "DataRow.tt"
            this.Write(" }} &\n        \\bitbox{25}[bgcolor=lightgray]{}\n\n        ");
            
            #line default
            #line hidden
            
            #line 50 "DataRow.tt"

            foreach(var f in this.Fields)
            {
        
            
            #line default
            #line hidden
            
            #line 54 "DataRow.tt"
            this.Write("        \\\\\n        \\begin{rightwordgroup}{");
            
            #line default
            #line hidden
            
            #line 55 "DataRow.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( f.Name ));
            
            #line default
            #line hidden
            
            #line 55 "DataRow.tt"
            this.Write("}\n        ");
            
            #line default
            #line hidden
            
            #line 56 "DataRow.tt"

                if (f.Length > 0)
                {
        
            
            #line default
            #line hidden
            
            #line 60 "DataRow.tt"
            this.Write("            \\bitbox{4}[bgcolor=lightergreen]{\\small length: ");
            
            #line default
            #line hidden
            
            #line 60 "DataRow.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( f.Length ));
            
            #line default
            #line hidden
            
            #line 60 "DataRow.tt"
            this.Write("} &\n            \\bitbox{28}{\\small ");
            
            #line default
            #line hidden
            
            #line 61 "DataRow.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( f.Data ?? "" ));
            
            #line default
            #line hidden
            
            #line 61 "DataRow.tt"
            this.Write("}\n        ");
            
            #line default
            #line hidden
            
            #line 62 "DataRow.tt"

                }
                else
                {
        
            
            #line default
            #line hidden
            
            #line 67 "DataRow.tt"
            this.Write("            \\bitbox{4}[bgcolor=lightergreen]{\\small length: ");
            
            #line default
            #line hidden
            
            #line 67 "DataRow.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( f.Length ));
            
            #line default
            #line hidden
            
            #line 67 "DataRow.tt"
            this.Write("} &\n            \\bitbox{28}[bgcolor=lightgray]{}\n        ");
            
            #line default
            #line hidden
            
            #line 69 "DataRow.tt"

                }
        
            
            #line default
            #line hidden
            
            #line 72 "DataRow.tt"
            this.Write("        \\end{rightwordgroup}\n        ");
            
            #line default
            #line hidden
            
            #line 73 "DataRow.tt"

            }
        
            
            #line default
            #line hidden
            
            #line 76 "DataRow.tt"
            this.Write("    \\end{leftwordgroup}\n");
            
            #line default
            #line hidden
            
            #line 77 "DataRow.tt"
 } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
        }
    }
    
    public class DataRowBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
