//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pg_protoexport.Templates {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    
    public partial class RowDescription : RowDescriptionBase {
        
        
        #line 54 "RowDescription.tt"
 float ITextTransformer.EstimateBytefieldRowCount() =>
        this.Render.Exact
            ? LatexHelper.CountExactRowsForMessage(this.Length, this.Render.RowWidthBytes)
            : 1 + this.Fields.Count;

        #line default
        #line hidden
        
        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 6 "RowDescription.tt"
 if (this.Render.Exact) {
    int rowWidth = this.Render.RowWidthBytes;
    int usedBytes = 5;

            
            #line default
            #line hidden
            
            #line 10 "RowDescription.tt"
            this.Write("    \\begin{leftwordgroup}{RowDescription}\n        \\bitbox{1}[bgcolor=lightcyan]{T" +
                    "} &\n        \\bitbox{4}[bgcolor=lightgreen]{length: ");
            
            #line default
            #line hidden
            
            #line 12 "RowDescription.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( this.Length ));
            
            #line default
            #line hidden
            
            #line 12 "RowDescription.tt"
            this.Write("}");
            
            #line default
            #line hidden
            
            #line 12 "RowDescription.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.EmitFixedBitbox("fields: " + this.FieldCount, 2, rowWidth, ref usedBytes) ));
            
            #line default
            #line hidden
            
            #line 12 "RowDescription.tt"

    int colIdx = 0;
    foreach (var col in this.Fields)
    {
        colIdx++;
    
            
            #line default
            #line hidden
            
            #line 18 "RowDescription.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.EmitWrappingCString("col" + colIdx + ": ", col.ColumnName, rowWidth, ref usedBytes) ));
            
            #line default
            #line hidden
            
            #line 18 "RowDescription.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.EmitFixedBitbox("tblOid: " + col.TableOid, 4, rowWidth, ref usedBytes) ));
            
            #line default
            #line hidden
            
            #line 18 "RowDescription.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.EmitFixedBitbox("idx: " + col.ColumnIndex, 2, rowWidth, ref usedBytes) ));
            
            #line default
            #line hidden
            
            #line 18 "RowDescription.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.EmitFixedBitbox("typOid: " + col.TypeOid, 4, rowWidth, ref usedBytes) ));
            
            #line default
            #line hidden
            
            #line 18 "RowDescription.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.EmitFixedBitbox("len: " + col.ColumnLength, 2, rowWidth, ref usedBytes) ));
            
            #line default
            #line hidden
            
            #line 18 "RowDescription.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.EmitFixedBitbox("typMod: " + col.TypeModifier, 4, rowWidth, ref usedBytes) ));
            
            #line default
            #line hidden
            
            #line 18 "RowDescription.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.EmitFixedBitbox(LatexHelper.ToFormatString(col.Format), 2, rowWidth, ref usedBytes) ));
            
            #line default
            #line hidden
            
            #line 18 "RowDescription.tt"

    }
    
            
            #line default
            #line hidden
            
            #line 21 "RowDescription.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.EmitPadToRowEnd(ref usedBytes, rowWidth) ));
            
            #line default
            #line hidden
            
            #line 21 "RowDescription.tt"
            this.Write("\n    \\end{leftwordgroup}\n");
            
            #line default
            #line hidden
            
            #line 23 "RowDescription.tt"
 } else { 
            
            #line default
            #line hidden
            
            #line 24 "RowDescription.tt"
            this.Write("\n    \\begin{leftwordgroup}{Row Description}\n        \\bitbox{1}[bgcolor=lightcyan]" +
                    "{T} &\n        \\bitbox{4}[bgcolor=lightgreen]{length: ");
            
            #line default
            #line hidden
            
            #line 27 "RowDescription.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( this.Length ));
            
            #line default
            #line hidden
            
            #line 27 "RowDescription.tt"
            this.Write("} &\n        \\bitbox{2}{\\tiny fields \\\\ \\tiny ");
            
            #line default
            #line hidden
            
            #line 28 "RowDescription.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( this.FieldCount ));
            
            #line default
            #line hidden
            
            #line 28 "RowDescription.tt"
            this.Write("} &\n        \\bitbox{25}[bgcolor=lightgray]{}\n\n        ");
            
            #line default
            #line hidden
            
            #line 31 "RowDescription.tt"

            int colIndex = 0;
            foreach(var column in this.Fields)
            {
                colIndex++;
        
            
            #line default
            #line hidden
            
            #line 37 "RowDescription.tt"
            this.Write("        \\\\\n\n        \\begin{rightwordgroup}{column ");
            
            #line default
            #line hidden
            
            #line 39 "RowDescription.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( colIndex ));
            
            #line default
            #line hidden
            
            #line 39 "RowDescription.tt"
            this.Write(" \\\\ ");
            
            #line default
            #line hidden
            
            #line 39 "RowDescription.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.Unescape(column.ColumnName) ));
            
            #line default
            #line hidden
            
            #line 39 "RowDescription.tt"
            this.Write("}\n            \\bitbox{14}{name: ");
            
            #line default
            #line hidden
            
            #line 40 "RowDescription.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.Unescape(column.ColumnName) ));
            
            #line default
            #line hidden
            
            #line 40 "RowDescription.tt"
            this.Write("} &\n            \\bitbox{4}{\\small table oid: ");
            
            #line default
            #line hidden
            
            #line 41 "RowDescription.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( column.TableOid ));
            
            #line default
            #line hidden
            
            #line 41 "RowDescription.tt"
            this.Write("} &\n            \\bitbox{2}{\\rotatebox{90}{\\tiny index: ");
            
            #line default
            #line hidden
            
            #line 42 "RowDescription.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( column.ColumnIndex ));
            
            #line default
            #line hidden
            
            #line 42 "RowDescription.tt"
            this.Write("}} &\n            \\bitbox{4}{\\small type oid: ");
            
            #line default
            #line hidden
            
            #line 43 "RowDescription.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( column.TypeOid ));
            
            #line default
            #line hidden
            
            #line 43 "RowDescription.tt"
            this.Write("} &\n            \\bitbox{2}{\\rotatebox{90}{\\tiny length: ");
            
            #line default
            #line hidden
            
            #line 44 "RowDescription.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( column.ColumnLength ));
            
            #line default
            #line hidden
            
            #line 44 "RowDescription.tt"
            this.Write("}} &\n            \\bitbox{4}{\\rotatebox{90}{\\parbox{1cm}{\\tiny type \\\\ modifier: ");
            
            #line default
            #line hidden
            
            #line 45 "RowDescription.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( column.TypeModifier ));
            
            #line default
            #line hidden
            
            #line 45 "RowDescription.tt"
            this.Write("}}} &\n            \\bitbox{2}{\\rotatebox{90}{\\tiny ");
            
            #line default
            #line hidden
            
            #line 46 "RowDescription.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( LatexHelper.ToFormatString(column.Format) ));
            
            #line default
            #line hidden
            
            #line 46 "RowDescription.tt"
            this.Write("}}\n\n        \\end{rightwordgroup}\n        ");
            
            #line default
            #line hidden
            
            #line 49 "RowDescription.tt"

            }
        
            
            #line default
            #line hidden
            
            #line 52 "RowDescription.tt"
            this.Write("    \\end{leftwordgroup}\n");
            
            #line default
            #line hidden
            
            #line 53 "RowDescription.tt"
 } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
        }
    }
    
    public class RowDescriptionBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
